'use client';

import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });
import { useRouter } from 'next/navigation';
import './layout.css';

export const metadata = {
  title: 'Firebase',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();
  const navegarHome = () => {
    router.push('/');
  };
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <div className="navbar">
          <button onClick={navegarHome}>Home</button>
        </div>
        {children}
      </body>
    </html>
  );
}
